# LAB 2 : Data Preprocessing Tools

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv(r"C:\Users\Admin\Downloads\employee_performance_dataset.csv")

In [4]:
dataset.head()

Employee_ID  Age   Department   Job_Role  Experience_Years   Salary  \
0         1001   50        Sales   Engineer              15.0  94895.0   
1         1002   36  Engineering    Manager              12.0  62307.0   
2         1003   29        Sales  Executive              29.0  84098.0   
3         1004   42    Marketing  Executive              18.0  90921.0   
4         1005   40        Sales   Engineer              16.0  35486.0   

   Performance_Rating  
0                   3  
1                   2  
2                   3  
3                   1  
4                   2

In [5]:
dataset.columns

Index(['Employee_ID', 'Age', 'Department', 'Job_Role', 'Experience_Years',
       'Salary', 'Performance_Rating'],
      dtype='object')

In [6]:
dataset.shape

(120, 7)

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Employee_ID         120 non-null    int64  
 1   Age                 120 non-null    int64  
 2   Department          120 non-null    object 
 3   Job_Role            120 non-null    object 
 4   Experience_Years    119 non-null    float64
 5   Salary              119 non-null    float64
 6   Performance_Rating  120 non-null    int64  
dtypes: float64(2), int64(3), object(2)
memory usage: 6.7+ KB


In [8]:
dataset.describe()

Employee_ID         Age  Experience_Years         Salary  \
count   120.000000  120.000000        119.000000     119.000000   
mean   1060.500000   40.016667         18.386555   74173.722689   
std      34.785054   10.991963         10.073551   26448.766806   
min    1001.000000   22.000000          0.000000   31062.000000   
25%    1030.750000   30.000000         11.000000   53162.500000   
50%    1060.500000   40.500000         19.000000   69298.000000   
75%    1090.250000   48.250000         27.000000   96121.500000   
max    1120.000000   59.000000         34.000000  119930.000000   

       Performance_Rating  
count          120.000000  
mean             3.041667  
std              1.169614  
min              1.000000  
25%              2.000000  
50%              3.000000  
75%              4.000000  
max              5.000000

In [9]:
dataset.describe(include = 'object')

Department   Job_Role
count         120        120
unique          5          5
top            HR  Executive
freq           32         27

## Preprocessing Steps

### Step 1 : Divide dataframe into input and output Featutres

In [10]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]

In [11]:
print(X)

     Employee_ID  Age   Department    Job_Role  Experience_Years    Salary
0           1001   50        Sales    Engineer              15.0   94895.0
1           1002   36  Engineering     Manager              12.0   62307.0
2           1003   29        Sales   Executive              29.0   84098.0
3           1004   42    Marketing   Executive              18.0   90921.0
4           1005   40        Sales    Engineer              16.0   35486.0
..           ...  ...          ...         ...               ...       ...
115         1116   53  Engineering   Executive               8.0   91529.0
116         1117   53  Engineering  Consultant               6.0  114665.0
117         1118   25    Marketing   Executive              27.0   61921.0
118         1119   51           HR    Engineer              13.0   63307.0
119         1120   58    Marketing   Executive              30.0   57355.0

[120 rows x 6 columns]


In [12]:
print(Y)

0      3
1      2
2      3
3      1
4      2
      ..
115    4
116    3
117    2
118    3
119    1
Name: Performance_Rating, Length: 120, dtype: int64


### Step 2: Handle the missing values in Dataset

In [15]:
!pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/62/27/585859e72e117fe861c2079bcba35591a84f801e21bc1ab85bce6ce60305/scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/f5/6f/e6e5aff77ea2a48dd96808bb51d7450875af154ee7cbe72188afb0b37929/scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     -------------------------------------- 60.8/60.8 kB 537.5 kB/s eta 0:00:00
  Obtaining dependency information for threadpoolctl>=3.1.0 from https://files.pythonhosted.org/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.1 M


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(dataset.iloc[:, 4:6]) 
dataset.iloc[:, 4:6] = imputer.transform(dataset.iloc[:, 4:6])


In [23]:
print(X)

     Employee_ID  Age   Department    Job_Role  Experience_Years    Salary
0           1001   50        Sales    Engineer              15.0   94895.0
1           1002   36  Engineering     Manager              12.0   62307.0
2           1003   29        Sales   Executive              29.0   84098.0
3           1004   42    Marketing   Executive              18.0   90921.0
4           1005   40        Sales    Engineer              16.0   35486.0
..           ...  ...          ...         ...               ...       ...
115         1116   53  Engineering   Executive               8.0   91529.0
116         1117   53  Engineering  Consultant               6.0  114665.0
117         1118   25    Marketing   Executive              27.0   61921.0
118         1119   51           HR    Engineer              13.0   63307.0
119         1120   58    Marketing   Executive              30.0   57355.0

[120 rows x 6 columns]


## Step 3 : Encoding categorical data

In [40]:
dataset['Department'].value_counts()

Department
HR             32
Marketing      30
Engineering    27
Finance        17
Sales          14
Name: count, dtype: int64

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',
                                      OneHotEncoder(), 
                                      [0])], 
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [30]:
print(X)

[[1.0000e+00 0.0000e+00 1.0000e+00 ... 1.5000e+01 9.4895e+04 3.0000e+00]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 1.2000e+01 6.2307e+04 2.0000e+00]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 2.9000e+01 8.4098e+04 3.0000e+00]
 ...
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 2.7000e+01 6.1921e+04 2.0000e+00]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 1.3000e+01 6.3307e+04 3.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 3.0000e+01 5.7355e+04 1.0000e+00]]


In [31]:
Y.value_counts()

Performance_Rating
3    44
4    29
2    18
1    16
5    13
Name: count, dtype: int64

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [33]:
print(Y)

[2 1 2 0 1 2 3 1 1 0 4 2 2 4 0 4 2 1 2 3 2 4 2 3 2 3 2 0 0 1 0 0 3 2 3 4 2
 3 3 2 1 1 1 1 1 4 3 0 1 0 2 2 3 2 3 4 0 3 2 2 2 3 3 3 4 3 4 3 3 2 0 3 2 2
 4 1 2 3 3 2 3 3 0 0 3 2 1 2 2 2 2 2 2 3 1 3 2 4 2 4 3 1 3 2 2 0 2 2 2 4 1
 2 2 0 2 3 2 1 2 0]


### Step 4 : Splitting Data into Training and Testing

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, 
                                                    dataset['Performance_Rating'], 
                                                    test_size=0.3, 
                                                    random_state=1)


In [36]:
print(X_train)

[[0.0000e+00 1.0000e+00 1.0000e+00 ... 4.0000e+00 7.4261e+04 4.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 2.5000e+01 9.6040e+04 4.0000e+00]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 3.2000e+01 9.2856e+04 4.0000e+00]
 ...
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 0.0000e+00 5.7192e+04 3.0000e+00]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 1.9000e+01 4.0975e+04 3.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 2.0000e+01 6.9081e+04 4.0000e+00]]


### Step 5 : Feature Scaling

In [37]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, 6:] = sc.fit_transform(X_train[:, 6:])
X_test[:, 6:] = sc.transform(X_test[:, 6:])


In [38]:
print(X_train)

[[ 0.          1.          1.         ... -1.481062   -0.08579889
   0.84452403]
 [ 1.          0.          0.         ...  0.67920128  0.73191686
   0.84452403]
 [ 1.          0.          1.         ...  1.39928904  0.61237018
   0.84452403]
 ...
 [ 1.          0.          1.         ... -1.89254072 -0.72667267
  -0.01017499]
 [ 0.          1.          1.         ...  0.0619832  -1.33555721
  -0.01017499]
 [ 1.          0.          0.         ...  0.16485288 -0.28028751
   0.84452403]]
